kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testingpsp-psp
  labels:
    app: testingpsp
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - testingpsp