apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testingpsp-psp
  labels:
    app: testingpsp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testingpsp-psp
subjects:
  - kind: ServiceAccount
    name: testingpsp
    namespace: default