apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: kube-system
  namespace: kube-system
spec:
  endpoints:
  - interval: 30s
    port: cert-exporter
  - interval: 30s
    port: metrics
  - interval: 30s
    targetPort: 8000
  selector:
    matchLabels:
      giantswarm.io/service-type: managed
