apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-psp
  labels:
    app: prometheus
    prometheus: k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-psp
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring