apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: helloworld
    kubernetes.io/ingress.class: nginx.ingress.kubernetes.io
  name: helloworld
  namespace: default
spec:
  rules:
  - host: helloworld.7sae2.k8s.gorilla.eu-central-1.aws.gigantic.io
    http:
      paths:
      - backend:
          serviceName: helloworld
          servicePort: 8080
        path: /

