apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "port-scan-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "port-scan-exporter.name" . }}
    helm.sh/chart: {{ include "port-scan-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch