{{- if .Values.prometheusOperator.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: {{ include "port-scan-exporter.name" . }}
    helm.sh/chart: {{ include "port-scan-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "port-scan-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - interval: 30s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "port-scan-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}